name: Blogpost.com Actions

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Installing Dependencies"
          npm install
      - name: Run Linting
        run: |
          echo "Running Lint..."
          npm run lint
